name: Fetch Multi-Category News

on:
  schedule:
    # Run every 3 hours for comprehensive coverage
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        npm install @supabase/supabase-js
        npm install rss-parser
        npm install node-fetch
        npm install dotenv
    
    - name: Fetch and Insert Multi-Category News
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        NODE_TLS_REJECT_UNAUTHORIZED: '0'  # Allow self-signed certificates
        NODE_OPTIONS: '--tls-min-v1.0 --tls-max-v1.3'  # TLS version range
      run: |
        node scripts/fetch-multi-category-news.mjs
    
    - name: Log Success
      run: echo "Multi-category news fetched successfully at $(date)"